package: service_bw
version: '1.3'
author: 'Friends Of REDAXO'

page:
    title: translate:service_bw_title
    perm: admin[]
    pjax: false
    icon: rex-icon rex-icon-template
    subpages:
        overview:
            title: 'translate:overview'
        config:
            title: translate:config
            icon: rex-icon fa-book
            itemClass: pull-right
